name: Run Prettier Formatting

on: 
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Prettier
      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Prettier Bot
          author_email: prettier-bot@example.com
          message: 'Committing Prettier changes'
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
